In [19]:
import tensorflow as tf
print(f"Tensorflow Version: {tf.__version__}")

Tensorflow Version: 2.15.0


In [20]:
mnist = tf.keras.datasets.mnist

(xtrain, ytrain), (xtest, ytest) = mnist.load_data()

# Pixel values are 0 - 255
# Divide by 255 to make this scaled 0 to 1
xtrain, xtest = xtrain / 255.0, xtest / 255.0

In [21]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape = (28, 28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10) 
])

In [22]:
predictions = model(xtrain[:1]).numpy()
predictions # model provides logits or log-odds scores

array([[-0.21394804, -0.02652837, -1.4654506 ,  1.3777212 , -0.8914868 ,
         0.00311746, -0.6552822 ,  0.17834036, -0.07913668,  0.52436364]],
      dtype=float32)

In [23]:
tf.nn.softmax(predictions).numpy() # converts logits to probabilities 

array([[0.06889566, 0.08309735, 0.0197093 , 0.33841142, 0.03498972,
        0.08559772, 0.04431216, 0.10199069, 0.07883874, 0.14415726]],
      dtype=float32)

In [24]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) # define loss function for training

In [26]:
loss_fn(ytrain[:1], predictions).numpy() # untrained model

2.4580965

In [27]:
model.compile(optimizer='adam', # configure and compile the model
              loss=loss_fn,
              metrics=['accuracy'])

In [28]:
model.fit(xtrain, ytrain, epochs=20) # train model

Epoch 1/20
1875/1875 [==============================] - 2s 837us/step - loss: 0.2906 - accuracy: 0.9159
Epoch 2/20
1875/1875 [==============================] - 1s 767us/step - loss: 0.1397 - accuracy: 0.9584
Epoch 3/20
1875/1875 [==============================] - 2s 802us/step - loss: 0.1037 - accuracy: 0.9679
Epoch 4/20
1875/1875 [==============================] - 1s 744us/step - loss: 0.0845 - accuracy: 0.9737
Epoch 5/20
1875/1875 [==============================] - 1s 743us/step - loss: 0.0734 - accuracy: 0.9766
Epoch 6/20
1875/1875 [==============================] - 1s 771us/step - loss: 0.0637 - accuracy: 0.9790
Epoch 7/20
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0577 - accuracy: 0.9818
Epoch 8/20
1875/1875 [==============================] - 2s 844us/step - loss: 0.0512 - accuracy: 0.9830
Epoch 9/20
1875/1875 [==============================] - 2s 829us/step - loss: 0.0479 - accuracy: 0.9845
Epoch 10/20
1875/1875 [==============================] - 2s 888us/

In [29]:
model.evaluate(xtest, ytest, verbose=2) # about 98% accurate

313/313 - 0s - loss: 0.0774 - accuracy: 0.9805 - 225ms/epoch - 718us/step


[0.07735303044319153, 0.9804999828338623]

In [30]:
probability_model = tf.keras.Sequential([ # build a model that gives probabilities
  model,
  tf.keras.layers.Softmax()
])

In [31]:
probability_model(xtest[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.8278258e-09, 2.6886919e-12, 3.0339153e-10, 3.6664983e-07,
        3.8138158e-15, 1.5176637e-09, 8.5108357e-18, 9.9999952e-01,
        4.5607247e-09, 8.9661633e-08],
       [2.6578819e-11, 7.7106918e-08, 9.9999988e-01, 2.0074047e-10,
        4.6185583e-30, 5.3147018e-11, 4.6775349e-13, 1.7086667e-22,
        1.6455496e-13, 2.8614797e-21],
       [9.7972086e-13, 9.9999392e-01, 3.6187615e-07, 5.1877380e-10,
        1.0366556e-06, 6.6902184e-10, 5.5911049e-09, 3.7171251e-06,
        9.3328407e-07, 1.3576651e-12],
       [9.9999976e-01, 3.3483259e-17, 3.2002270e-10, 1.5165092e-13,
        7.3200536e-11, 1.6190970e-11, 1.8599563e-07, 1.2868044e-09,
        2.9800203e-15, 7.9250553e-09],
       [1.1131073e-10, 9.2853671e-18, 3.7533212e-08, 4.4628629e-15,
        9.9983788e-01, 2.4360099e-12, 2.9886182e-10, 6.3461485e-09,
        9.3845331e-12, 1.6213204e-04]], dtype=float32)>